config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'about', to: "home#about"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  resources :shops
  resources :machines
  resources :shop_machines, only: [:create, :edit, :update, :destroy]
  get "/shop_machines/:id/new", to: 'shop_machines#new'

  resources :events, only: [:edit, :create, :update, :destroy]

end

app/models/shop_machine.rb
class ShopMachine < ApplicationRecord
  belongs_to :shop
  belongs_to :machine

  validates :shop_id,    presence: true
  validates :machine_id, presence: true
  validates :price,      presence: true,
                         length: {maximum: 20}
  validates :own,        presence: true
end

app/controllers/shop_machines_controller.rb
class ShopMachinesController < ApplicationController
  before_action :set_shop
  before_action :user_is_owner?

  def new
    @shop_machines = ShopMachine.new
    @machines = Machine.where.not(id: @shop.machine_ids)
  end

  def create
      success_count = 0
      create_params = shop_machines_params
      create_params[:own].each_with_index do |own, i|
        next if own.to_i <= 0
        shop_machine = ShopMachine.create(shop_id:    create_params[:shop_id],
                                          machine_id: create_params[:machine_id][i],
                                          own:        create_params[:own][i],
                                          price:      create_params[:price][i] )
        if  shop_machine.save
          success_count += 1
        end
      end

      if success_count == 0
        flash[:danger] = "登録に失敗しました"
      else
        flash[:success] = "#{success_count}件のデータを登録しました"
      end
      redirect_to shop_path(create_params[:shop_id])
  end

  def edit
    @shop_machines = ShopMachine.where(shop_id: @shop.id)
    @machines = Machine.where(id: @shop.machine_ids)
  end

  def update
    # params[:shop_machines].values
    success_count = 0

    update_shop_machines_params.values.each do |param|
      @shop_machine = ShopMachine.find_by(id: param[:id])

      if param[:own].to_i <= 0
        @shop_machine.destroy
        success_count += 1
      elsif @shop_machine[:own] == param[:own].to_i && @shop_machine[:price] == param[:price]
        next
      elsif @shop_machine.update_attributes(param)
        success_count += 1
      end
    end

    if success_count == 0
      flash[:danger] = "編集に失敗しました"
    else
      flash[:success] = "#{success_count}件のデータを更新しました"
    end
      redirect_to @shop
  end

  private

    def set_shop
      @shop = Shop.find_by(id: params[:id])
    end

    def update_shop_machines_params
      params.permit(shop_machines: [:id, :shop_id, :machine_id, :price, :own])[:shop_machines]
    end

    def create_shop_machines_params
      params.require(:shop_machines).map do |m|
        m.permit(:shop_id, :machine_id, :price, :own)
      end
    end

    def shop_machines_params
      params.require(:shop_machine).permit(:shop_id, machine_id: [], price: [], own: [])
    end

end

app/views/shop_machines/edit.html.haml
- provide :title, "登録ゲームの編集"
.container.atl-table-form.mx-auto
  %p
    設置台数は半角数字で入力して下さい。
    %br また、0を入力すると削除されます。
  = form_tag shop_machine_path, method: :patch do
    %table.mx-auto
      %thead.atl-table-head
        %tr
          %th.w-15rem
            ゲームタイトル
          %th.w-6rem
            メーカー
          %th.w-6rem
            ジャンル
          %th.w-6rem
            料金
          %th.w-6rem
            設置台数
      %tbody.atl-table-body
        - @shop_machines.each do |shop_machine|
          = fields_for "shop_machines[]", shop_machine do |f|
            = render 'shared/error_messages', object: f.object
            = f.hidden_field :id, value: shop_machine.id
            %tr
              %th
                = show_self_image(shop_machine.machine, 30)
                = shop_machine.machine.title
              %td
                = shop_machine.machine.maker
              %td
                = shop_machine.machine.genre
              %td
                = f.text_field  :price, class:"text-right "
              %td
                = f.text_field  :own, class:"text-right"
    = button_tag type: "submit", class: "atl-submit mt-5" do
      %i.far.fa-check-square.fa-2x
      登録する

app/views/shop_machines/new.html.haml
- provide :title, "ゲームの登録"
.container.atl-table-form.mx-auto
  %p
    設置台数は半角数字で入力して下さい。
    %br 設置台数に1以上を入力すると登録されます。
  = form_for @shop_machines, url: shop_machines_path(params[:id]), method: :post do |f|
    %table.mx-auto
      %thead.atl-table-head
        %tr
          %th.w-15rem
            ゲームタイトル
          %th.w-6rem
            メーカー
          %th.w-6rem
            ジャンル
          %th.w-6rem
            料金
          %th.w-6rem
            設置台数
      %tbody.atl-table-body
        = f.hidden_field :shop_id, value: @shop.id
        - @machines.each do |machine|
          = f.hidden_field :machine_id, multiple: true, value: machine.id
          %tr
            %th
              = show_self_image(machine, 30)
              = machine.title
            %td
              = machine.maker
            %td
              = machine.genre
            %td.text-right
              = f.text_field  :price, multiple: true, class:"text-right "
            %td
              = f.text_field  :own, multiple: true, class:"text-right "
    = button_tag type: "submit", class: "atl-submit mt-5" do
      %i.far.fa-check-square.fa-2x
      登録する