config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'about', to: "home#about"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  resources :shops
  resources :machines
  resources :shop_machines, only: [:create, :edit, :update, :destroy]
  get "/shop_machines/:id/new", to: 'shop_machines#new'

  resources :events, only: [:edit, :create, :update, :destroy]

end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_one :tag, dependent: :destroy
  has_many :event, dependent: :destroy
  has_many :shop_machine, dependent: :destroy
  has_many :machine, through: :shop_machine
  accepts_nested_attributes_for :tag
  geocoded_by :adress
  after_validation :geocode
  validates :user_id,  uniqueness: true
  validates :shop_name, presence: true,
                        length: {maximum: 50}
  validates :tel,       presence: true,
                        length: {maximum: 20},
                        uniqueness: true
  validates :adress,          length: {maximum: 50}
  validates :access,          length: {maximum: 50}
  validates :business_hours,  length: {maximum: 50}
  validates :nearest_station, length: {maximum: 50}
  validates :shop_info,       length: {maximum: 255}
  validates :official_url,    length: {maximum: 100}
  mount_uploader :image, ImageUploader

  def self.search_adress(query)
    if query
      where(['adress LIKE ?', "#{query}%"])
    else
      all
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  def index

    # 全件表示リンク・リダイレクト用
    if params[:search].nil?
      @shops = Shop.page(params[:page])
      flash.now[:info] = "全店舗を表示します。"
      return
    end

    # エリアが選択された時、マッチするshop_idをids[:from_adress]に代入
    ids = {}
    if params[:search][:adress].present?
      ids[:from_adress] = Shop.search_adress(params[:search][:adress]).map(&:id)
      @query_adress = params[:search][:adress]
    # エリアもゲームも選択しなかった時は全件表示
    elsif params[:search][:machine_ids].nil?
      @shops = Shop.page(params[:page])
      flash.now[:info] = "全店舗を表示します。"
      return
    end

    # 選択されたゲームを持つshop_idをids[:from_machine]に代入
    # 参考URL https://orangelog.site/rails/search-filter-associated-models/
    @machine_ids = params[:search][:machine_ids]
    if @machine_ids.present?
      conditions = {}
      conditions[:shop_machines] = {}
      conditions[:shop_machines][:machine_id] = @machine_ids.map(&:to_i)
      ids[:from_machine] = ShopMachine.where(machine_id: conditions[:shop_machines][:machine_id]).group(:shop_id).having('count(shop_id) = ?', @machine_ids.length).map(&:shop_id)
      @query_machines = Machine.find(@machine_ids)

    end

    # ids[:from_adress] と ids[:from_machine] から 出力するid配列 ids[:shop] を求める
    if ids[:from_adress].present? && ids[:from_machine].present?
      ids[:shop] = ids[:from_adress] & ids[:from_machine]
    elsif ids[:from_adress].nil?
      ids[:shop] = ids[:from_machine]
    elsif ids[:from_machine].nil?
      ids[:shop] = ids[:from_adress]
    end

    # ids[:shop] で抽出
    if ids[:shop].present?
      @shops = Shop.where(id: ids[:shop]).page(params[:page])
    else
      redirect_to root_path, notice: "該当する店舗がありませんでした。"
    end
  end

  def show
    @shop = Shop.find(params[:id])
    @new_event = Event.new
    @events = @shop.event
  end

  def new
    redirect_to shop_path(current_user) if current_user.shop.present?
    @shop = Shop.new
    @shop.build_tag
  end

  def edit
    @shop = Shop.find(params[:id])
    unless @shop == current_user.shop || current_user.role == 2
      flash[:notice] = "権限がありません。"
      redirect_to shop_path(@shop)
    end
  end

  def create
    if user_signed_in? && current_user.shop.present?
      redirect_to root_path
    else
      @shop = current_user.build_shop(shop_params)
      @shop.build_tag(tag_params)
      if @shop.save
        flash[:success] = "登録しました"
        redirect_to shop_path(@shop)
      else
        render 'new'
      end
    end
  end

  def update
    @shop = Shop.find(params[:id])

    if  (@shop == current_user.shop || current_user.role == 2)  &&
        @shop.update_attributes(shop_params)   &&
        @shop.tag.update_attributes(tag_params)
      flash[:success] = "更新しました。"
      redirect_to "/shops/#{@shop.id}"
    else
      render 'edit'
    end
  end

  def destroy
    Shop.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to root_path
  end

  private

    def shop_params
      params.require(:shop).permit( :shop_name, :business_hours,  :tel,
                                    :adress,    :nearest_station, :access,
                                    :shop_info, :official_url,    :image,
                                    :latitude,  :longitude  )
    end

    def tag_params
      params.require(:tag).permit(  :emoney,     :paseli,  :parking,
                                    :open24h,    :older18, :smoking,
                                    :hand_towel, :locker,  :wifi )
    end
end

app/views/shops/_form.html.haml
= form_for @shop do |f|
  = render 'shared/error_messages', object: f.object
  .row.justify-content-center.mb-4
    .col-lg-5
      #img_field.mx-auto{onClick: "$('#file').click()"}
        - if has_shop?(current_user)
          = show_self_image(@shop)
        - else
          アイコン画像を選択
      .row.align-items-center.justify-content-center.mb-5
        %p.pt-4.pr-3 画像クリックで変更
        %label.image-label.atl-btn.mt-3
          %i.fa.fa-image.fa-2x
          画像を選択
          = f.file_field :image, class: "none", id: "file"
      .row
        .col.form-tags.mx-auto
          = fields_for :tag do |t|
            .row.text-center
              %p.mx-auto タグをクリックで ON / OFF 切り替え出来ます。
            .row
              .col
                = t.check_box      :emoney, {:checked => @shop.tag.emoney} , "true", "false"
                = t.label          :emoney, "電子マネー", class: "pr-3"
                %br
                = t.check_box      :parking, {:checked => @shop.tag.parking}, "true", "false"
                = t.label          :parking, "駐車場アリ", class: "pr-3"
                %br
                = t.check_box      :open24h, {:checked => @shop.tag.open24h}, "true", "false"
                = t.label          :open24h, "24時間営業", class: "pr-3"
                %br
                = t.check_box      :older18, {:checked => @shop.tag.older18}, "true", "false"
                = t.label          :older18, "18歳未満禁止", class: "pr-3"
                %br
              .col
                = t.check_box      :hand_towel, {:checked => @shop.tag.hand_towel}, "true", "false"
                = t.label          :hand_towel, "おしぼり", class: "pr-3"
                %br
                = t.check_box      :locker, {:checked => @shop.tag.locker}, "true", "false"
                = t.label          :locker, "無料ロッカー", class: "pr-3"
                %br
                = t.check_box      :wifi, {:checked => @shop.tag.wifi}, "true", "false"
                = t.label          :wifi, "無料Wifi", class: "pr-3"
                %br
            .form-smoking.mb-5
              = t.radio_button  :smoking, 0, {:checked => somoking_cheked?( @shop, 0) }
              = t.label          :smoking, "禁煙", value: 0, class: "pr-3"
              %br
              = t.radio_button  :smoking, 1, {:checked => somoking_cheked?( @shop, 1) }
              = t.label          :smoking, "分煙", value: 1, class: "pr-3"
              %br
              = t.radio_button  :smoking, 2, {:checked => somoking_cheked?( @shop, 2) }
              = t.label          :smoking, "喫煙可", value: 2, class: "pr-3"

    .col-lg-7
      .text-left.mb-4
        .form-column
          %i.fas.fa-pencil-alt
          = f.label       :shop_name
        .form-required.my-auto
          ※ 必須
        %br
        = f.text_field  :shop_name, class: "mt-1 ml-3 atl-textfield"
      .text-left.mb-4
        .form-column
          %i.fas.fa-pencil-alt
          = f.label       :business_hours
        %br
        = f.text_field  :business_hours, class: "mt-1 ml-3 atl-textfield"
      .text-left.mb-4
        .form-column
          %i.fas.fa-pencil-alt
          = f.label       :tel
        .form-required.my-auto
          ※ 必須
        %br
        = f.text_field  :tel, class: "mt-1 ml-3 atl-textfield"
      .text-left.mb-4
        .form-column
          %i.fas.fa-pencil-alt
          = f.label       :adress
        %br
        = f.text_field  :adress, class: "mt-1 ml-3 atl-textfield"
      .text-left.mb-4
        .form-column
          %i.fas.fa-pencil-alt
          = f.label       :nearest_station
        %br
        = f.text_field  :nearest_station, class: "mt-1 ml-3 atl-textfield"
      .text-left.mb-4
        .form-column
          %i.fas.fa-pencil-alt
          = f.label       :access
        %br
        = f.text_field  :access, class: "mt-1 ml-3 atl-textfield"
      .text-left.mb-4
        .form-column
          %i.fas.fa-pencil-alt
          = f.label       :official_url
        %br
        = f.text_field  :official_url, class: "mt-1 ml-3 atl-textfield"
      .text-left.mb-4
        .form-column
          %i.fas.fa-pencil-alt
          = f.label       :shop_info
        %br
        = f.text_area   :shop_info, class: "mt-1 ml-3 atl-textarea"


    = button_tag type: "submit", class: "atl-submit" do
      %i.far.fa-check-square.fa-2x
      登録する

:javascript
  $(function(){
    $fileField = $('#file')
    $($fileField).on('change', $fileField, function(e) {
      file = e.target.files[0]
      reader = new FileReader(),
      $preview = $("#img_field");

      reader.onload = (function(file) {
        return function(e) {
          $preview.empty();
          $preview.append($('<img>').attr({
            src: e.target.result,
            width: "100%",
            class: "preview",
            title: file.name
          }));
        };
      })(file);
      reader.readAsDataURL(file);
    });
  });

app/views/shops/_machines.html.haml
.atl-table.mx-auto.mb-5
  %table
    %thead.atl-table-head
      %tr
        %th.w-25rem
          ゲームタイトル
        %th.w-8rem
          メーカー
        %th.w-8rem
          ジャンル
        %th.w-6rem
          料金
        %th.w-6rem
          設置台数
    %tbody.atl-table-body
      - @shop.shop_machine.each do |sm|
        %tr
          %th
            = link_to machine_path(sm.machine_id) do
              = show_self_image(sm.machine, 30)
              = "#{sm.machine.title}"
          %td
            = "#{sm.machine.maker}"
          %td
            = "#{sm.machine.genre}"
          %td
            = "#{sm.price}"
          %td
            = "#{sm.own} 台"
.mb-5
  - if has_edit_authority?(@user, @shop)
    = link_to "/shop_machines/#{@shop.id}/new", class: "atl-btn" do
      %i.fa.fa-plus.fa-2x
      登録
    = link_to edit_shop_machine_path, class: "atl-btn" do
      %i.fas.fa-edit.fa-2x
      編集

app/views/shops/_new_event.html.haml
.container.my-4
  = form_for @new_event do |f|
    = render 'shared/error_messages', object: f.object
    = f.hidden_field :shop_id, value: @shop.id
    .row.justify-content-left
      = f.label       :content, class:"form-column ml-3"
    .row.justify-content-center
      = f.text_area   :content, class: "atl-textarea"
    .row.justify-content-left.mt-3
      = f.label      :event_date, class: "mt-3 ml-3 form-column"
    #datetimepicker4.row.mt-1{data: {target: {input: "nearest"} } }
      .atl-calendar{data: {target: "#datetimepicker4", toggle: "datetimepicker"} }
        %i.fa.fa-calendar
      = f.text_field :event_date, class: "atl-datefield datetimepicker-input", placeholder:"カレンダーで入力", data: {target: "#datetimepicker4"}
      .col.text-center
        = button_tag type: "submit", class: "atl-submit" do
          %i.fa.fa-calendar-plus.fa-2x
          登録する

app/views/shops/_shop.html.haml
.shops-child.text-left
  .shop-element-head
    = link_to shop_path(shop) do
      %i.fas.fa-home
      = shop.shop_name
  .shop-element.pt-1.mb-5
    .row.justify-content-end
      .col-xs-3.ml-4
        = link_to show_self_image(shop,100), shop_path(shop)
      - if @query_machines
        %table.col.machine-list
          %tbody
            - shop.shop_machine.each do |sm|
              - if @machine_ids.include?(sm.machine_id.to_s)
                %tr
                  %td.w-15rem.text-center.py-1
                    = sm.machine.title
                  %td.w-4rem
                    = sm.price
                  %td.w-4rem
                    = "#{sm.own} 台"
      - else
        .col
          = shop.shop_info
    .row.ml-2.mr-1.my-1
      = render 'tags', shop: shop

app/views/shops/_shop_status.html.haml
%span.content-title 営業時間
.content-border
.content-child= "#{@shop.business_hours}"
%span.content-title TEL
.content-border
.content-child= "#{@shop.tel}"
%span.content-title 住所
.content-border
.content-child= "#{@shop.adress}"
%span.content-title 最寄駅
.content-border
.content-child= "#{@shop.nearest_station}"
%span.content-title 更新日
.content-border
.content-child= "#{@shop.updated_at.strftime("%Y年%m月%d日 %H:%M:%S")}"
= link_to "#Access", class: "atl-btn" do
  %i.far.fa-hand-point-right.fa-2x
  アクセス
= link_to @shop.official_url, class: "atl-btn", target: :_blank do
  %i.far.fa-hand-point-right.fa-2x
  公式サイト
- if has_edit_authority?(@user, @shop)
  = link_to edit_shop_path, class: "atl-btn" do
    %i.fas.fa-edit.fa-2x
    編集
  - if current_user.role == 2
    = link_to shop_path, class: "atl-btn", method: :delete, data: {confirm: "デバッグ用のコマンドです。本当に店舗データを削除してよろしいですか？"} do
      %i.fa.fa-trash.fa-2x
      削除

app/views/shops/_tags.html.haml
%span.far.fa-credit-card{class: "#{shop.tag.emoney ? 'tag' : 'tag-not'}"}
  = " 電子マネー"

%span.fa.fa-parking{class: "#{shop.tag.parking ? 'tag' : 'tag-not'}"}
  = " 駐車場"

%span.tag{class: "#{shop.tag.open24h ? 'tag' : 'tag-not'}"}
  = " 24時間営業"

%span.fa.fa-ban{class: "#{shop.tag.older18 ? 'tag' : 'tag-not'}"}
  = " R18"

%span{class: "#{shop.tag.hand_towel ? 'tag' : 'tag-not'}"}
  = " おしぼり"

%span.fa.fa-lock{class: "#{shop.tag.locker ? 'tag' : 'tag-not'}"}
  = " 無料ロッカー"

%span.fa.fa-wifi{class: "#{shop.tag.wifi ? 'tag' : 'tag-not'}"}
  = " 無料Wifi"

- case shop.tag.smoking
  - when 0 then
    %span.tag.fas.fa-smoking-ban
      = " 禁煙"
  - when 1 then
    %span.tag.fas.fa-smoking
      = " 分煙"
  - else
    %span.tag.fas.fa-smoking
      = " 喫煙可"

app/views/shops/edit.html.haml
- provide :title, "店舗データの変更"
= render 'form'

app/views/shops/index.html.haml
- provide :title, "検索結果"
%p.mb-2.text-left.pl-5
  = "エリア条件："
  - if @query_adress
    = "#{@query_adress}"
  - else
    = "なし"

%p.mb-2.text-left.pl-5
  = "ゲーム条件："
  - if @query_machines
    - @query_machines.each do |machine|
      = " [#{machine.title}] "
  -else
    = "なし"

%p.mb-2.text-left.pl-5
  = @shops.total_count
  件のお店が見つかりました。
  %br
  - unless @shops.total_count == 1
    = "#{@shops.offset_value + 1} 〜 #{@shops.offset_value + @shops.length}件目を表示しています。"

.shops
  - @shops.each do |shop|
    = render 'shop', shop: shop

.my-2
  = paginate @shops

.text-center
  = link_to root_path, class: "atl-btn" do
    %i.fas.fa-search.fa-2x
    条件を変えて検索する

app/views/shops/new.html.haml
- provide :title, "店舗データ登録"
= render 'form'

app/views/shops/show.html.haml
- provide :title, @shop.shop_name
.row.py-4
  .col
    = show_self_image(@shop,300)
    .row.mt-3
      .col
        = render 'tags', shop: @shop
  .col.text-left
    = render 'shop_status'
.row.justify-content-center
  .shop-info
    %p.py-2
      = simple_format @shop.shop_info
.container.py-4.ml-2
  .row
    .col-xs-3.shop-element-head
      %i.fa.fa-flag
      = link_to "イベント", "#Events", role: "button", data:{toggle: "collapse"}, aria: {expanded: "true", controls: "Events"}
  #Events.collapse.show.shop-element
    #event_list
      = render './events/events'
    = render './events/new_event'

.container.py-4.ml-2
  .row
    .col-xs-3.shop-element-head
      %i.fa.fa-desktop
      = link_to "設置ゲーム", "#Machines", role: "button", data:{toggle: "collapse"}, aria: {expanded: "true", controls: "Machines"}
  #Machines.collapse.show.shop-element
    = render 'machines'

.container.py-4.ml-2
  .row
    .col-xs-3.shop-element-head
      %i.fa.fa-map-marker-alt
      = link_to "アクセス", "#Access", role: "button", data:{toggle: "collapse"}, aria: {expanded: "true", controls: "Access"}
  #Access.collapse.show.shop-element
    %p= "#{@shop.access}"
    - if @shop.latitude
      .googlemap.mx-auto.mb-5
        #map
    - else
      .text-center.mb-5
        実在する住所を入力すると、ここにGoogleMapが表示されます。

:javascript

  $(function () {
      $('#datetimepicker4').datetimepicker({
          format: 'L'
      });
  });

  handler = Gmaps.build('Google');
  handler.buildMap({
    provider: {
      zoom: 12,
      center:    new google.maps.LatLng(#{@shop.latitude}, #{@shop.longitude}),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    },
    internal: {id: 'map'}}, function(){
    handler.fitMapToBounds();
  });