config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'about', to: "home#about"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  resources :shops
  resources :machines
  resources :shop_machines, only: [:create, :edit, :update, :destroy]
  get "/shop_machines/:id/new", to: 'shop_machines#new'

  resources :events, only: [:edit, :create, :update, :destroy]

end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_one :tag, dependent: :destroy
  has_many :event, dependent: :destroy
  has_many :shop_machine, dependent: :destroy
  has_many :machine, through: :shop_machine
  accepts_nested_attributes_for :tag
  geocoded_by :adress
  after_validation :geocode
  validates :user_id,  uniqueness: true
  validates :shop_name, presence: true,
                        length: {maximum: 50}
  validates :tel,       presence: true,
                        length: {maximum: 20},
                        uniqueness: true
  validates :adress,          length: {maximum: 50}
  validates :access,          length: {maximum: 50}
  validates :business_hours,  length: {maximum: 50}
  validates :nearest_station, length: {maximum: 50}
  validates :shop_info,       length: {maximum: 255}
  validates :official_url,    length: {maximum: 100}
  mount_uploader :image, ImageUploader

  def self.search_adress(query)
    if query
      where(['adress LIKE ?', "#{query}%"])
    else
      all
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @shop = Shop.new
    @machines = Machine.all
  end

  def about
  end

  def result
  end

  def shop
  end
end

app/views/home/about.html.haml
- provide :title, "About"
%h1.pb-5
  %span.title> AtlAcade
  とは？
%p 全国のアミューズメント施設（ゲームセンター）を検索できるサービスです。
%p 場所で探す、置いてるゲームで探す、お店のイベントで探す、等が出来ます。
%p.py-3 「AtlAcade」という言葉は"地図帳"を意味する「Atlas」と”ゲームセンター”である「Arcade」から来ている造語です。

%p.pt-3 アカウントを登録するともっと便利に使えます。
= link_to new_user_registration_path, class: "atl-btn ml-4" do
  %i.far.fa-plus-square.fa-2x
  アカウントの登録

app/views/home/index.html.haml
%section.atl-base
  .container
    #Signboard
      .title_underline
        %span.title> AtlAcade
      .hello.mt-3
        .row
          .col
            = image_tag("/images/logo.png", height: 200)
          .col
            %p
              - if current_user
                ようこそ
                = "#{@user.nickname}さん、こんにちは"
              - else
                ようこそ、こんにちは
            %p
              %span.font-atl>AtlAcade
              は全国のアミューズメント施設を検索します。

            詳しくはこちらへ
            = link_to about_path, class: "atl-btn mt-3" do
              %i.fas.fa-info-circle.fa-2x
              ABOUT
  .container.text-center.my-5
    %p 今日は何をお探しですか？
    %p 素晴らしい店舗やゲームとの出会いを願っています。
    = link_to shops_path, class: "atl-btn mr-3" do
      %i.fas.fa-home.fa-2x
      ショップ一覧
    = link_to machines_path, class: "atl-btn ml-3" do
      %i.fa.fa-desktop.fa-2x
      ゲーム一覧
#Search.container.main-border.text-center.pb-5
  .main-title.mx-auto.py-3
    検索
  = form_with scope: :search ,url: shops_path, method: :get, local: true do |f|
    .area-select
      %span エリア指定：
      = f.select :adress, perfectures, prompt: "都道府県を選択"
    %br
    .text-left
      .machine-items-head
        ゲーム指定
    .machine-items.mb-3
      .py-2
        タイトルをクリックで選択出来ます。
      - @machines.each do |machine|
        = f.check_box  :machine_ids, {multiple: true, include_hidden: false, id: "machine_#{machine.id}", mtitle: "#{machine.title}"}, machine[:id]
        = f.label     :machine_ids, machine.title, for: "machine_#{machine.id}"
      #machine_query
        選択したゲームがありません
    = button_tag type: "submit", class: "atl-submit my-3" do
      %i.fas.fa-search.fa-2x
      検索
    %br 何も指定しないと全てのお店を表示します。
#GestUsers.text-center.py-5
  - unless user_signed_in?
    %p ログイン・新規登録はこちら
    = link_to new_user_session_path, class: "atl-btn ml-4" do
      %i.fas.fa-sign-in-alt.fa-2x
      ログイン
    = link_to new_user_registration_path, class: "atl-btn ml-4" do
      %i.fas.fa-user-plus.fa-2x
      アカウントの登録

:javascript
  $(function() {
    $('input[name="search[machine_ids][]"]').change(function() {
      var machines = [];
      $('input[name="search[machine_ids][]"]:checked').each(function() {
        machines.push($(this).attr("mtitle"));
      });
      $('#machine_query').html("選択されたゲーム<br>" + machines.join("、 "));
    });
  });