config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'about', to: "home#about"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  resources :shops
  resources :machines
  resources :shop_machines, only: [:create, :edit, :update, :destroy]
  get "/shop_machines/:id/new", to: 'shop_machines#new'

  resources :events, only: [:edit, :create, :update, :destroy]

end

app/views/layouts/_bootstrap.html.haml
/ Required meta tags
%meta{:charset => "utf-8"}/
%meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
/ Bootstrap CSS
%link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", :integrity => "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", :rel => "stylesheet"}/

app/views/layouts/_flash_message.html.haml
- flash.each do |message_type, message|
  .container.text-center.py-4.flash-area
    = content_tag(:div, message, class: "flash py-2 alert alert-#{message_type}")

app/views/layouts/_footer.html.haml
%footer
  .container
    .row
      .col
      .col
        %ul
          %h6
            %span.font-atl>AtlAcade
          %li= link_to "GitHub","https://github.com/Rikiya3702/atlacade", target: :_blank
          %li= link_to "Home", root_path
          %li= link_to "About", about_path
          %li= link_to "アカウント登録", new_user_registration_path
          %li= link_to "ログイン", new_user_session_path
      .col
        %ul
          %br
          %li= link_to "店舗一覧", shops_path
          %li= link_to "店舗データ登録", new_shop_path
          %li= link_to "ゲーム一覧", machines_path
          %li= link_to "ゲーム登録", new_machine_path
      .col
    .row
      .col
        %h6 外部リンク
        %br
    .row
      .col
        %ul
          %h6 アミューズメント業界を作っている代表的な企業様
          %li= link_to "コナミアミューズメント", "https://www.konami.com/amusement/", target: :_blank
          %li= link_to "セガ・インタラクティブ", "https://sega-interactive.co.jp/", target: :_blank
          %li= link_to "バンダイナムコエンターテインメント", "https://www.bandainamcoent.co.jp/", target: :_blank
          %li= link_to "タイトー", "https://www.taito.co.jp/", target: :_blank
          %li= link_to "ラウンドワン", "https://www.round1.co.jp/", target: :_blank
          %li= link_to "アドアーズ", "https://www.adores.jp/", target: :_blank
          %li= link_to "サードプラネット", "https://3rd-planet.jp/", target: :_blank
          %li= link_to "山崎屋", "https://www.yamazakiya.co.jp/", target: :_blank
          %li= link_to "あなたのウェアハウス", "https://www.warehousenet.jp/", target: :_blank
      .col
        %ul
          %h6 本アプリケーションに使用したサービスなど。
          %h6  主にデザイン面で使用させて頂きました。
          %li= link_to "Lucidchart", "https://www.lucidchart.com/pages/ja", target: :_blank
          %li= link_to "Hatchful", "https://hatchful.shopify.com/ja/", target: :_blank
          %li= link_to "Google Fonts", "https://fonts.google.com/", target: :_blank
          %li= link_to "Font Awesome", "https://fontawesome.com/", target: :_blank
          %li= link_to "Bootstrap", "https://getbootstrap.jp/", target: :_blank
          %li= link_to "FLAT ICON DESIGN", "http://flat-icon-design.com/", target: :_blank
          %li= link_to "Faker", "https://github.com/faker-ruby/faker", target: :_blank
          %li= link_to "Gimei", "https://github.com/willnet/gimei", target: :_blank
          %li= link_to "Kaminari", "https://github.com/kaminari/kaminari", target: :_blank
  %p.text-center.mb-0 ©︎2019 Rikiya Horikoshi

app/views/layouts/_head.html.haml
%title AtlAcade
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
= csrf_meta_tags
= render 'layouts/bootstrap'

= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

/webフォント
<link href="https://fonts.googleapis.com/css?family=Poiret+One&Kosugi&display=swap&subset=japanese" rel="stylesheet">

/GoogleMap
%script{async: "", defer: "defer", src: "https://maps.googleapis.com/maps/api/js?key=AIzaSyDbGiz-wtzVFXKIpNFyQNZxqd4XAVhJ_Bs"}
%script(src="//maps.google.com/maps/api/js?v=3.23")
%script(src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js")
%script(src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript')
%script(src='/javascripts/gmaps_google.js')

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-dark.header-base.navbar-expand-md
    .logo2.mr-5
      = link_to "AtlAcade", root_path
    %button.navbar-toggler.atl-navtoggle{"aria-controls" => "navmenu1", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navmenu1", "data-toggle" => "collapse", :type => "button"}
      %i.fas.fa-bars
    #navmenu1.collapse.navbar-collapse.navbar-right
      .navbar-nav
        - if user_signed_in?
          = link_to edit_user_registration_path(@user) do
            .nav-item.nav-link
              = show_self_image(@user, 30)
              = @user.nickname
          - if has_shop?(current_user)
            = link_to shop_path(@user.shop.id) do
              .nav-item.nav-link
                = show_self_image(@user.shop, 30)
                = @user.shop.shop_name
        = link_to root_path(anchor: "Search"), class: "nav-item nav-link" do
          %i.fas.fa-search
          検索
        = link_to about_path, class: "nav-item nav-link" do
          %i.fas.fa-info-circle
          ABOUT
        - if user_signed_in?
          - if !has_shop?(current_user) && @user.role != 0
            = link_to new_shop_path, class: "nav-item nav-link" do
              %i.far.fa-plus-square
              店舗データ登録
          = link_to destroy_user_session_path, class: "nav-item nav-link", method: :delete do
            %i.fas.fa-sign-out-alt
            ログアウト
        - else
          = link_to new_user_session_path, class: "nav-item nav-link" do
            %i.fas.fa-sign-in-alt
            ログイン
          = link_to new_user_registration_path, class: "nav-item nav-link" do
            %i.fas.fa-user-plus
            アカウントの登録

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render 'layouts/head'
  %body
    = render 'layouts/header'
    .atl-base
      = render 'layouts/flash_message'
      - unless current_page?(root_path)
        .container.text-center.pt-4
          .main-border.pb-5
            .main-title
              = yield(:title)
            = yield
      - else
        = yield
      - unless current_page?(root_path)
        .text-center.py-5
          = link_to :back, class: "atl-btn" do
            %i.far.fa-arrow-alt-circle-left.fa-2x
            戻る
    = render 'layouts/footer'